advances:
  - name: deposit
    doc: |
      Deposit Ether to the honeypot.
      This input should be sent through the Ether portal.

  - name: withdraw
    doc: |
      Withdraw the given value from honeypot.
      The contract only process this input if it come from the owner.
    fields:
      - name: value
        type: uint

reports:
  - name: currentBalance
    doc: |
      Return the current balance of the honeypot.
    fields:
      - name: balance
        type: uint
