name: Tests

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Add support for RISC-V containers.
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up sunodo
      run: yarn global add @sunodo/cli@0.9.3

    # Download the images in a previous step to avoid timing out the tests.
    - name: Download sunodo Docker images
      run: |
        docker pull cartesi/rollups-cli:1.0.2
        docker pull sunodo/devnet:1.1.1
        docker pull sunodo/rollups-node:0.5.0
        docker pull traefik:v2.10
        docker pull postgres:13-alpine
        docker pull redis:6-alpine

    - name: Test examples
      env:
        EGGTEST_RUN_INTEGRATION: true
        EGGTEST_VERBOSE: true
      run: go test -p 1 -v ./...
