# Workflow to run the examples

name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Add support for more platforms with QEMU (necessary to run RISC-V containers)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install sunodo
      run: yarn global add @sunodo/cli

    - name: Test examples
      run: ./internal/scripts/test-examples.sh -c
